version: "3.8"

services:
  ros-noetic:
    build: .
    container_name: ros-noetic-container
    volumes:
      - ./workspace:/workspace
    environment:
      - DISPLAY=${DISPLAY}
    devices:
      - "/dev/dri:/dev/dri"
    network_mode: host
    stdin_open: true
    tty: true
    command: bash
